version: "3.9"

x-app-environment: &x-app-environment
  # App
  APP_NAME: "pub-sub"
  APP_VERSION: "1.0.0"
  # Logger
  LOG_LEVEL: "debug"
  # gRPC
  GRPC_PORT: "8080"

services:
  pubsub:
    build:
      context: .
    container_name: pubsub_service
    environment:
      <<: *x-app-environment
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/app", "--version"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge